//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTCharacterRangeFrameConverter.h"
#import "DVTLineRangeCharacterRangeConverter.h"
#import "DVTSourceCodeLanguageEditorView.h"
#import "DVTSourceLandmarkItemContainer.h"
#import "DVTSourceModelProvider.h"
#import "DVTTextInsertionPointLocator.h"

@protocol DVTSourceEditorViewProtocol <DVTSourceModelProvider, DVTSourceCodeLanguageEditorView, DVTSourceLandmarkItemContainer, DVTLineRangeCharacterRangeConverter, DVTCharacterRangeFrameConverter, DVTTextInsertionPointLocator>
@end

