//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IBDiagnosticsHandlerConfigurator.h"
#import "IBVerboseDescriptionProvider.h"

@class NSDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface IBAbstractPlatformToolExecutionContext : NSObject <IBDiagnosticsHandlerConfigurator, IBVerboseDescriptionProvider>
{
    long long _isBusyCount;
    NSObject<OS_dispatch_queue> *_busyCountToolQueue;
    double _timeStampFromLastIdleOrBusy;
    NSDictionary *_additionalEnvironment;
}

+ (void)initialize;
@property(copy, nonatomic) NSDictionary *additionalEnvironment; // @synthesize additionalEnvironment=_additionalEnvironment;
- (void).cxx_destruct;
- (id)ib_verboseDescription;
@property(readonly, copy) NSString *description;
- (void)setIdleTimeToAtLeast:(double)arg1;
- (BOOL)isIdleForAtLeast:(double)arg1;
- (double)timeSinceLastIdleOrBusy;
- (void)decrementBusy;
- (void)incrementBusy;
- (id)busyCountQueue;
- (void)configureDiagnosticsHandler:(id)arg1;
- (BOOL)populateEnvironment:(id)arg1 launchContext:(id)arg2 error:(id *)arg3;
- (void)populateDYLDFrameworkSearchPaths:(id)arg1 launchContext:(id)arg2;
@property(readonly) NSString *runtimeDestinationHint;
- (id)environmentWithLaunchContext:(id)arg1 error:(id *)arg2;
- (id)launchAndConnectToToolWithLaunchContext:(id)arg1 toolProxyClass:(Class)arg2 proxyDelegate:(id)arg3 shouldRaiseOnFailures:(BOOL)arg4 error:(id *)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

