//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface IBGenericDeviceTypeDescription : NSObject <NSCopying>
{
}

- (unsigned long long)hash;
- (BOOL)isEqualToDescription:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)identifier;
- (void)populateEnvironment:(id)arg1 launchContext:(id)arg2;

@end

