//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IBICARImageSet.h"

#import "IBICAbstractCollectionChild.h"

@class NSString;

@interface IBICARImageSet (DisplayAdditions) <IBICAbstractCollectionChild>
+ (id)itemsFromOverlayOrnament:(id)arg1;
+ (id)arImagePaths:(id)arg1;
+ (id)itemsFromImageReps:(id)arg1;
- (BOOL)applyContentFromDropIndicator:(id)arg1;
- (id)synthesizeAncestorsIfNeededToAllowHostingInContainer:(id)arg1;
- (id)overviewCapsuleSpecification;
- (id)thumbnail;
- (id)icon;
- (id)bitmap;
- (id)dragImage;
- (id)image;
- (id)imageRep;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

