//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTLayoutView_ML.h"

@interface IBICAssetCollectionViewItemContainer : DVTLayoutView_ML
{
    BOOL _showCross;
    id <IBICAssetCollectionViewItemContainerDelegate> _delegate;
}

@property(nonatomic) __weak id <IBICAssetCollectionViewItemContainerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL showCross; // @synthesize showCross=_showCross;
- (void).cxx_destruct;
- (id)description;
- (void)didCompleteLayout;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutBottomUp;
- (void)layoutTopDown;
@property(retain, nonatomic) DVTLayoutView_ML *content;

@end

