//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IDEMediaType, NSDictionary, NSSet, NSString;

@protocol IDEResourceManager <NSObject>
@property(copy, nonatomic) NSDictionary *variantForMatching;
- (id <DVTInvalidation>)registerResourceObserver:(void (^)(NSSet *))arg1;
- (id)firstResourceValueOfMediaType:(IDEMediaType *)arg1 withRuntimeName:(NSString *)arg2;
- (NSSet *)availableRuntimeNamesForMediaType:(IDEMediaType *)arg1;
@end

