//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColor.h"

@interface NSColor (IBNSCatalogColorIBSupport)
+ (id)ib_newNSCatalogColorWithCoder:(id)arg1 zone:(struct _NSZone *)arg2;
@end

