//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IBResourceManager.h"

@interface IBCocoaTouchResourceManager : IBResourceManager
{
}

+ (id)systemMediaRepository;
+ (id)missingImage;
- (void)populateIssues:(id)arg1 forResourceReferences:(id)arg2;
- (id)typesForDefaultMediaRepositories;
- (id)placeholderResourceIconForMediaType:(id)arg1;
- (id)scaleVariableForForcingOneXImages;
- (id)placeholderResourceContentForMediaType:(id)arg1 runtimeName:(id)arg2 originalValue:(id)arg3;

@end

