//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IBBasePreviewDocumentEditor.h"

@interface IBCocoaTouchPreviewDocumentEditor : IBBasePreviewDocumentEditor
{
    BOOL _includeDeviceNameInTitle;
}

- (id)displayNameForApplyingRecipe:(id)arg1 toObject:(id)arg2;
- (BOOL)isValidRecipe:(id)arg1;
- (void)userAddedNewConfiguration:(id)arg1;
- (void)rotatePreviewItem:(id)arg1;
- (void)rotateRecipe:(id)arg1;
- (void)preparePreviewResultView:(id)arg1;
- (void)applyScale:(double)arg1 toPreviewResultView:(id)arg2 withOriginalImage:(id)arg3;
- (void)menuNeedsUpdate:(id)arg1;
- (void)refreshControlState;
- (id)applicableVersions;
- (id)applicableIdioms;
- (Class)previewRecipeClass;
- (id)installEditorObservations;

@end

