//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XRFrameActivity;

@protocol XRFrameActivityManager <NSObject>
-     // Error parsing type: ^Ac16@0:8, name: _shouldYieldFlag
- (void)_activityYielded:(XRFrameActivity *)arg1;
@end

