//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet;

@interface XRMobileAgentTeam : NSObject
{
    NSSet *_members;
}

@property(readonly, nonatomic) NSSet *members; // @synthesize members=_members;
- (void).cxx_destruct;
- (id)init;
- (id)initWithMembers:(id)arg1;

@end

