//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol IDEIntentBuilderGroupEditable <NSObject>
@property(readonly, nonatomic, getter=isHiddenWhenEmpty) BOOL hiddenWhenEmpty;
@property(readonly) BOOL canRemoveItems;
@property(readonly) BOOL canRenameItems;
@property(readonly) BOOL canEditItems;
@end

