//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEIntentBuilderEnumValue.h"

@interface IDEIntentBuilderEnumValue (EditorAdditions)
+ (id)keyPathsForValuesAffectingRemovable;
+ (id)keyPathsForValuesAffectingEditable;
@property(readonly, getter=isDisplayNameEditable) BOOL displayNameEditable;
@property(readonly, getter=isRemovable) BOOL removable;
@property(readonly, getter=isEditable) BOOL editable;
@end

