//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEIntentBuilderIntentResponseCode.h"

#import "IDEIntentBuilderLocalizableStringProvider.h"

@class NSArray, NSDictionary;

@interface IDEIntentBuilderIntentResponseCode (EditorAdditions) <IDEIntentBuilderLocalizableStringProvider>
@property(readonly, copy, nonatomic) NSArray *parameters;
@property(readonly, copy, nonatomic) NSDictionary *localizableStringsDictionary;
@property(readonly, nonatomic, getter=isEditable) BOOL editable;
@property(readonly, nonatomic, getter=isRemovable) BOOL removable;
@end

