//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEIntentBuilderIntentParameterCombination.h"

#import "IDEIntentBuilderLocalizableStringProvider.h"

@class NSArray, NSDictionary, NSImage;

@interface IDEIntentBuilderIntentParameterCombination (EditorAdditions) <IDEIntentBuilderLocalizableStringProvider>
+ (id)parameterCombinationFromPasteboardWithIntent:(id)arg1;
+ (BOOL)canPasteFromPasteboardWithIntent:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *localizableStringsDictionary;
@property(readonly, nonatomic) NSImage *statusImage;
- (void)copyToPasteboard;

// Remaining properties
@property(readonly, copy, nonatomic) NSArray *parameters;
@end

