//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEInspectorViewController.h"

@interface IDEIntentBuilderDocumentInspector : IDEInspectorViewController
{
}

+ (id)keyPathsForValuesAffectingSelectedObjects;
+ (id)keyPathsForValuesAffectingSelectedModel;
+ (id)keyPathsForValuesAffectingSourceLanguage;
- (id)selectedModel;
- (id)selectedItems;
@property unsigned long long sourceLanguage; // @dynamic sourceLanguage;

@end

