//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEIntentBuilderIntent.h"

@class NSArray;

@interface IDEIntentBuilderIntent (Bindings)
+ (id)keyPathsForValuesAffectingSelectedCategories;
@property(retain, nonatomic) NSArray *selectedCategories;
@end

