//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDETextSubstitutionTemplateInstantiationContext.h"

#import "NSCopying.h"

@class DVTFilePath, DVTVersion, IDEIntentBuilderIntent, IDEIntentBuilderModel, NSDictionary, NSSet;

@interface IDEIntentBuilderIntentTemplateInstantiationContext : IDETextSubstitutionTemplateInstantiationContext <NSCopying>
{
    BOOL _automaticInvocation;
    NSSet *_files;
    NSSet *_intents;
    IDEIntentBuilderModel *_model;
    IDEIntentBuilderIntent *_intent;
    NSDictionary *_deploymentTargets;
    DVTVersion *_swiftVersion;
    DVTFilePath *_modelFilePath;
}

@property(retain) DVTFilePath *modelFilePath; // @synthesize modelFilePath=_modelFilePath;
@property(getter=isAutomaticInvocation) BOOL automaticInvocation; // @synthesize automaticInvocation=_automaticInvocation;
@property(retain) DVTVersion *swiftVersion; // @synthesize swiftVersion=_swiftVersion;
@property(retain) NSDictionary *deploymentTargets; // @synthesize deploymentTargets=_deploymentTargets;
@property(retain) IDEIntentBuilderIntent *intent; // @synthesize intent=_intent;
@property(retain) IDEIntentBuilderModel *model; // @synthesize model=_model;
@property(retain) NSSet *intents; // @synthesize intents=_intents;
@property(retain) NSSet *files; // @synthesize files=_files;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

