//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDateFormatter.h"

@interface NSDateFormatter (IBNSDateFormatterWidgetIntegration)
- (void)setIbShadowedFormatterBehavior:(long long)arg1;
- (long long)ibShadowedFormatterBehavior;
- (void)setIbShadowedDateFormat:(id)arg1;
- (id)ibShadowedDateFormat;
- (id)ibDefaultDataValueForTableView:(id)arg1;
- (id)ibLocalLocalizableStringsAttributeKeyPaths;
- (id)ibLocalAttributeKeyPaths;
@end

