//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@protocol GPUTimelineGraphPlaneInfo
- (BOOL)isLineGraph;
- (BOOL)isVisible;
- (unsigned long long)sortingIndex;
- (unsigned long long)groupIndex;
- (long long)maxValue;
- (NSString *)planeDescription;
- (NSString *)subtitle;
- (NSString *)name;
@end

