//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUTimelineGraphDefaultTheme.h"

__attribute__((visibility("hidden")))
@interface GPUTraceCounterGraphTheme : GPUTimelineGraphDefaultTheme
{
}

- (id)referencePlaneHighlightColor;
- (id)highlightColor;
- (id)referencePlaneColor;
- (id)groupColor;
- (struct CGPoint)planeNameOffset;
- (id)planeNameColor;
- (id)planeNameFont;

@end

