//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMenu, NSString, NSView;

@protocol IDEFilterControlBarTarget <NSObject>
@property(readonly, nonatomic) NSView *view;
- (NSString *)filterButtonAccessibilityDescription;
- (NSString *)filterButtonToolTip;
- (NSMenu *)filterButtonMenu;
- (NSString *)filterDefinitionIdentifier;
@end

