//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DBGColor.h"

#import "DBGExtendedColorPropertyValue.h"

@class NSString;

@interface DBGColor (DBGExtendedColorPropertyValue) <DBGExtendedColorPropertyValue>
- (id)dbg_colorName;
- (id)dbg_color;
- (id)dbg_catalogName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

