//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DBGDataSourceConnectionLegacy.h"

@interface DBGDataSourceConnectionLegacy_macOS : DBGDataSourceConnectionLegacy
{
}

+ (Class)dataSourceConnectionLibViewDebuggerHelperClass;
- (id)targetKitFamilyIdentifier;
- (id)libViewDebuggerSupportClassName;
- (BOOL)isObjectOfClassInteresting:(id)arg1;

@end

