//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DBGRenderableInstance : NSObject
{
    BOOL _selected;
    NSString *_identifier;
}

@property(nonatomic, getter=isSelected) BOOL selected; // @synthesize selected=_selected;
@property(copy) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;

@end

