//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface LOCIBElement : NSObject
{
    NSString *_identifier;
    NSString *_accessor;
    NSString *_value;
    NSString *_key;
    NSString *_type;
    NSString *_comment;
    NSString *_string;
    NSString *_restype;
}

@property(retain, nonatomic) NSString *restype; // @synthesize restype=_restype;
@property(retain, nonatomic) NSString *string; // @synthesize string=_string;
@property(retain, nonatomic) NSString *comment; // @synthesize comment=_comment;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(readonly) NSString *key; // @synthesize key=_key;
@property(retain, nonatomic) NSString *value; // @synthesize value=_value;
@property(retain, nonatomic) NSString *accessor; // @synthesize accessor=_accessor;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)stringsFileElement;
- (id)description;
- (id)initWithIdentifier:(id)arg1 accessor:(id)arg2 value:(id)arg3 type:(id)arg4 restype:(id)arg5;

@end

