//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEStackFrame.h"

@interface IDEStackFrame (IDEProductsUI)
+ (id)stackFrameWithThread:(id)arg1 analyticsLogStackFrame:(id)arg2 frameNumber:(long long)arg3 usingContext:(id)arg4;
@property(retain) id <DVTAnalyticsLogStackFrameProtocol> representativeAnalyticsLogStackFrame;
@end

