//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTAnnotationProvider.h"

@class IDEEditor;

@interface IDESourceCodeEditorAnnotationProvider : DVTAnnotationProvider
{
    IDEEditor *_editor;
}

+ (id)annotationProviderForContext:(id)arg1 error:(id *)arg2;
@property(retain) IDEEditor *editor; // @synthesize editor=_editor;
- (void).cxx_destruct;
- (void)providerWillUninstall;
- (id)initWithEditor:(id)arg1;

@end

