//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DVTDeviceTokenAction.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface DVTDNATokenConnectAction : NSObject <DVTDeviceTokenAction>
{
    NSString *_identifier;
    NSObject<OS_dispatch_queue> *_operationQueue;
}

- (void).cxx_destruct;
- (void)performForDeviceToken:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSString *identifier;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

