//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XCTProtocolVersion;

@protocol XCTDaemonProxyProviding <NSObject>
@property(readonly, copy) XCTProtocolVersion *protocolVersion;
@property(readonly) id <XCTestManager_DaemonConnectionInterface> proxy;
@end

