//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XCTDaemonRequest.h"

@class NSObject<OS_dispatch_semaphore>, NSString;

@interface XCTDaemonBarrierRequest : NSObject <XCTDaemonRequest>
{
    double _timeout;
    CDUnknownBlockType _timeoutHandler;
    NSObject<OS_dispatch_semaphore> *_dsem;
}

+ (id)minimumProtocolVersion;
@property(readonly) NSObject<OS_dispatch_semaphore> *dsem; // @synthesize dsem=_dsem;
@property(readonly, copy) CDUnknownBlockType timeoutHandler; // @synthesize timeoutHandler=_timeoutHandler;
@property(readonly) double timeout; // @synthesize timeout=_timeout;
- (void).cxx_destruct;
- (void)handleConnectionFailure:(id)arg1;
- (void)finish;
- (void)executeWithDaemonProxyProvider:(id)arg1;
- (id)initWithTimeout:(double)arg1 timeoutHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

