//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XCTConfigurableCallbackQueue.h"
#import "XCTConfigurableDebugLogger.h"

@protocol XCTDaemonSession <XCTConfigurableCallbackQueue, XCTConfigurableDebugLogger>
@property __weak id <XCTDaemonSessionDelegate> delegate;
- (void)invalidate;
@end

