//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTDaemonControl/XCTDaemonSession.h>

#import "XCTDaemonControlSession.h"
#import "XCTestManager_IDEInterface.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface XCTDaemonControlSession : XCTDaemonSession <XCTestManager_IDEInterface, XCTDaemonControlSession>
{
}

- (id)_XCT_reportSelfDiagnosisIssue:(id)arg1 description:(id)arg2;
- (id)_XCT_logDebugMessage:(id)arg1;
- (id)_XCT_handleCrashReportData:(id)arg1 fromFileWithName:(id)arg2;
- (void)requestSpindumpWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly) BOOL canRequestSpindumps;
- (void)collectLogArchiveFromStartDate:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly) BOOL canRequestLogArchives;
- (void)_synchronizeRemoteHostDiagnosticsAndRemapFilePath:(id)arg1 synchronizer:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)collectNewCrashReportsInDirectories:(id)arg1 matchingProcessNames:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly) BOOL canRequestCrashReports;
- (void)authorizeProcessWithIdentifier:(int)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly) BOOL canAuthorizeProcesses;
- (id)proxyChannelForConnection:(id)arg1;

// Remaining properties
@property(retain) NSObject<OS_dispatch_queue> *callbackQueue;
@property(readonly, copy) NSString *debugDescription;
@property __weak id <XCTDaemonSessionDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property __weak id <XCTDebugLogDelegate> logDelegate;
@property(readonly) Class superclass;

@end

