//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XCTConfigurableDebugLogger.h"
#import "XCTDaemonRequest.h"

@class NSString;

@interface XCTDaemonInitiateControlSessionRequest : NSObject <XCTDaemonRequest, XCTConfigurableDebugLogger>
{
    id <XCTDebugLogDelegate> _logDelegate;
    CDUnknownBlockType _completion;
}

+ (id)minimumProtocolVersion;
@property(readonly, copy) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property __weak id <XCTDebugLogDelegate> logDelegate; // @synthesize logDelegate=_logDelegate;
- (void).cxx_destruct;
- (void)handleConnectionFailure:(id)arg1;
- (void)_attemptVersion13APIWithDaemonProxy:(id)arg1;
- (void)_attemptVersion16APIWithDaemonProxy:(id)arg1;
- (void)executeWithDaemonProxyProvider:(id)arg1;
- (id)initWithCompletion:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

