//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DBGSnapshotManager.h"

@class DBGViewDebugger;

@interface DBGSnapshotManagerXcode : DBGSnapshotManager
{
    DBGViewDebugger *_viewDebugger;
}

@property __weak DBGViewDebugger *viewDebugger; // @synthesize viewDebugger=_viewDebugger;
- (void).cxx_destruct;
- (id)_displayableStringFromRawErrorMessage:(id)arg1;
- (void)logMessage:(id)arg1 userFacing:(BOOL)arg2;

@end

