//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class DBGViewObject;

@protocol DBGViewDebuggerDataSourceManager
- (void)setDataSource:(id)arg1 forViewObject:(DBGViewObject *)arg2;
- (id)dataSourceForViewObject:(DBGViewObject *)arg1;
@end

