//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DVTTestDeviceCloneCreator.h"

@class NSMapTable, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSURL;

@interface DVTTestSimulatorDeviceCloneCreator : NSObject <DVTTestDeviceCloneCreator>
{
    Class _serviceClass;
    Class _simulatorClass;
    id <DVTTestingSimDeviceSet> _deviceSet;
    NSURL *_customDeviceSetLocation;
    NSURL *_developerDirPath;
    NSMapTable *_simulatorClaims;
    NSMutableDictionary *_cloneNameIndexes;
    NSMutableDictionary *_cloneMap;
    NSObject<OS_dispatch_queue> *_queue;
    NSURL *_persistentMappingURL;
}

+ (void)setSharedCreator:(id)arg1;
+ (id)sharedCreator;
+ (void)setLogAspect:(id)arg1;
+ (id)logAspect;
@property(readonly) NSURL *persistentMappingURL; // @synthesize persistentMappingURL=_persistentMappingURL;
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly) NSMutableDictionary *cloneMap; // @synthesize cloneMap=_cloneMap;
@property(readonly) NSMutableDictionary *cloneNameIndexes; // @synthesize cloneNameIndexes=_cloneNameIndexes;
@property(readonly) NSMapTable *simulatorClaims; // @synthesize simulatorClaims=_simulatorClaims;
@property(readonly) NSURL *developerDirPath; // @synthesize developerDirPath=_developerDirPath;
@property(readonly) NSURL *customDeviceSetLocation; // @synthesize customDeviceSetLocation=_customDeviceSetLocation;
@property(readonly) id <DVTTestingSimDeviceSet> deviceSet; // @synthesize deviceSet=_deviceSet;
@property(readonly) Class simulatorClass; // @synthesize simulatorClass=_simulatorClass;
@property(readonly) Class serviceClass; // @synthesize serviceClass=_serviceClass;
- (void).cxx_destruct;
- (id)cloneMapSnapshot;
- (void)saveCloneMapSnapshotToDisk;
- (void)addClone:(id)arg1 ofDeviceWithIdentifier:(id)arg2;
- (void)recycleNameForClone:(id)arg1 ofDeviceWithIdentifier:(id)arg2;
- (unsigned long long)nameIndexForClone:(id)arg1;
- (void)reserveNameForClone:(id)arg1 ofDeviceWithIdentifier:(id)arg2;
- (id)generateUniqueNameForCloneOfDevice:(id)arg1;
- (BOOL)canCloneDevice:(id)arg1;
- (id)preexistingClones;
- (id)destroyDevice:(id)arg1;
- (id)destroyClone:(id)arg1;
- (id)shutdownClone:(id)arg1;
- (id)cloneDevice:(id)arg1;
- (void)dealloc;
- (id)finishInitialization;
- (id)initWithServiceClass:(Class)arg1 simulatorClass:(Class)arg2 developerDirURL:(id)arg3 customDeviceSetURL:(id)arg4 persistentMappingURL:(id)arg5;

@end

