//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, XCSourceTextBuffer;

@interface XCSourceEditorCommandInvocation : NSObject
{
    BOOL __cancelled;
    CDUnknownBlockType _cancellationHandler;
    NSString *_commandIdentifier;
    XCSourceTextBuffer *_buffer;
    id <XCSourceEditorCommand> __command;
}

@property(readonly) BOOL _cancelled; // @synthesize _cancelled=__cancelled;
@property(retain) id <XCSourceEditorCommand> _command; // @synthesize _command=__command;
@property(readonly) XCSourceTextBuffer *buffer; // @synthesize buffer=_buffer;
@property(readonly, copy) NSString *commandIdentifier; // @synthesize commandIdentifier=_commandIdentifier;
- (void).cxx_destruct;
@property(copy) CDUnknownBlockType cancellationHandler; // @synthesize cancellationHandler=_cancellationHandler;
- (void)_cancelCommand;
- (id)description;
- (id)initWithCommandIdentifier:(id)arg1 buffer:(id)arg2;

@end

