//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DebugHierarchyRequestAction.h"

@class DebugHierarchyRequestExecutionContext;

@protocol DebugHierarchyRequestObjectAction <DebugHierarchyRequestAction>
- (BOOL)targetsObjectIdentifiers:(id *)arg1;
- (void)performInContext:(DebugHierarchyRequestExecutionContext *)arg1 withObject:(id <DebugHierarchyObject>)arg2;
@end

