//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DebugHierarchyEntryPointProtocolHelper : NSObject
{
}

+ (id)debugHierarchyObjectsInGroupWithID:(id)arg1 outOptions:(id *)arg2 onEntryPointClass:(Class)arg3;
+ (id)debugHierarchyGroupingIDsOnClass:(Class)arg1;
+ (BOOL)classImplementsRequiredEntryPointMethods:(Class)arg1;

@end

