//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DebugHierarchyObjectInterface : NSObject
{
}

+ (id)propertyDescriptionsForClass:(Class)arg1 inContext:(id)arg2;
+ (id)valueForProperty:(id)arg1 withOutOptions:(id *)arg2 onObject:(id)arg3 inContext:(id)arg4 error:(id *)arg5;
+ (id)valueAndOptionsForProperty:(id)arg1 onObject:(id)arg2 inContext:(id)arg3;

@end

