//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DTXChannel;

@interface DVTiOSScreenshotClient : NSObject
{
    DTXChannel *_channel;
}

@property(retain) DTXChannel *channel; // @synthesize channel=_channel;
- (void).cxx_destruct;
- (id)requestScreenshotWithError:(id *)arg1;
- (void)dealloc;
- (id)initWithConnection:(id)arg1;

@end

