//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DYPShaderDebuggerThread.h"

@protocol DYPShaderDebuggerThreadVertex <DYPShaderDebuggerThread>
@property(readonly, nonatomic) unsigned long long instanceId;
@property(readonly, nonatomic) unsigned long long vertexId;
@end

