//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DYPShaderDebuggerROI.h"
#import "DYPShaderDebuggerROILocation.h"

@class NSString;

@interface GPUShaderDebuggerRegion : NSObject <DYPShaderDebuggerROI, DYPShaderDebuggerROILocation>
{
    unsigned long long _type;
}

+ (id)regionWithRegionOfInterest:(id)arg1 selectedThread:(id)arg2;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
- (id)initWithType:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

