//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <GPUDebuggerFoundation/GPUShaderDebuggerRegion.h>

#import "DYPShaderDebuggerROILocationPostTessellationVertex.h"
#import "DYPShaderDebuggerROIPostTessellationVertex.h"

@class NSArray, NSString;

@interface GPUShaderDebuggerPostTessellationVertexRegion : GPUShaderDebuggerRegion <DYPShaderDebuggerROIPostTessellationVertex, DYPShaderDebuggerROILocationPostTessellationVertex>
{
    unsigned long long _instanceId;
    NSArray *_patchIds;
    unsigned long long _patchId;
}

@property(readonly, nonatomic) unsigned long long patchId; // @synthesize patchId=_patchId;
@property(readonly, nonatomic) NSArray *patchIds; // @synthesize patchIds=_patchIds;
@property(readonly, nonatomic) unsigned long long instanceId; // @synthesize instanceId=_instanceId;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)initWithInstanceId:(unsigned long long)arg1 patchIds:(id)arg2 selectedPatchId:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) unsigned long long type;

@end

