//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <GPUDebuggerFoundation/GPUTraceResourceItem.h>

@interface GPUTraceSamplerItem : GPUTraceResourceItem
{
}

@property(readonly, nonatomic) id <DYSampler> samplerResourceObject;

// Remaining properties
@property(readonly, nonatomic) id <DYSampler> resourceObject; // @dynamic resourceObject;

@end

