//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IBBinaryArchiving.h"

@class NSDictionary, NSString;

@interface IBUIMetricRepresentation : NSObject <IBBinaryArchiving>
{
    NSDictionary *_keyValues;
}

@property(readonly, copy) NSDictionary *keyValues; // @synthesize keyValues=_keyValues;
- (void).cxx_destruct;
- (BOOL)isEqualToMetricRepresentation:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (void)applyToObject:(id)arg1;
- (void)encodeWithBinaryArchiver:(id)arg1;
- (id)initWithBinaryUnarchiver:(id)arg1;
- (id)initWithKeyValues:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

